import Product1 from "../assets/img/akkotiger.png";
import Product2 from "../assets/img/akkohonkai.png";
import Wireless from "../../../assets/wireless.png";
import Bluetooth from "../../../assets/bluetooth.png";
import Hotswap from "../../../assets/hotswap.png";
export const MostBuyData = [
  {
    id: 1,
    img_url: Product1,
    product_name: "Akko PC75B Plus Year Of Tiger",
    product_compatible: [Wireless, Bluetooth, Hotswap],
    brand: "Akko",
    keycap: "Bla Blo Keycap",
    switch: "Bla Blo Switch",
    layout: "85% TKL",
    weight: "1 KG",
    feature: ["Fast", "Convenient", "Golang"],
  },
  {
    id: 2,
    img_url: Product1,
    product_name: "Akko PC75B Plus Year Of Tiger",
    product_compatible: [Wireless, Bluetooth, Hotswap],
    brand: "Akko",
    keycap: "Bla Blo Keycap",
    switch: "Bla Blo Switch",
    layout: "85% TKL",
    weight: "1 KG",
    feature: ["Fast", "Convenient", "Golang"],
  },
  {
    id: 3,
    img_url: Product1,
    product_name: "Akko PC75B Plus Year Of Tiger",
    product_compatible: [Wireless, Bluetooth, Hotswap],
    brand: "Akko",
    keycap: "Bla Blo Keycap",
    switch: "Bla Blo Switch",
    layout: "85% TKL",
    weight: "1 KG",
    feature: ["Fast", "Convenient", "Golang"],
  },
  {
    id: 4,
    img_url: Product1,
    product_name: "Akko PC75B Plus Year Of Tiger",
    product_compatible: [Wireless, Bluetooth, Hotswap],
    brand: "Akko",
    keycap: "Bla Blo Keycap",
    switch: "Bla Blo Switch",
    layout: "85% TKL",
    weight: "1 KG",
    feature: ["Fast", "Convenient", "Golang"],
  },
  {
    id: 5,
    img_url: Product1,
    product_name: "Akko PC75B Plus Year Of Tiger",
    product_compatible: [Wireless, Bluetooth, Hotswap],
    brand: "Akko",
    keycap: "Bla Blo Keycap",
    switch: "Bla Blo Switch",
    layout: "85% TKL",
    weight: "1 KG",
    feature: ["Fast", "Convenient", "Golang"],
  },
];
